void _puts_recursion(char *s);
void _print_rev_recursion(char *s);
int _strlen_recursion(char *s);
int factorial(int n);
int _pow_recursion(int x, int y);
int _sqrt_recursion(int n);
int binary_search(int n, int low, int high);
int is_prime_number(int n);
int prime_helper(int n, int i);
int _putchar(char c);
